# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Raye Liu
tagline:          'A Personal Website'
description:      'Senior, majoring Operations Research & Information Engineering at <a href="https://www.engineering.cornell.edu/programs-departments/operations-research-and-information-engineering" target="_blank">Cornell University</a>, with a minor in CS and Math.'
url:              https://raye2333.github.io/indiv-web/
baseurl:          ""
encoding:         utf-8

author:
  name:           'Raye Liu'
  url:            zl285@cornell.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Raye2333/indiv-web
